# Generated by Django 4.1.2 on 2022-10-31 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_delete_paymentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_order_id', models.CharField(max_length=22)),
                ('payment_id', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('receipt', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=10)),
                ('signature', models.CharField(max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.PositiveIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
