# Generated by Django 4.1.2 on 2022-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='created_at',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='receipt',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='signature',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
