# Generated by Django 4.1.2 on 2022-10-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentorder_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='status',
        ),
    ]
