# Generated by Django 4.1.2 on 2022-11-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(default='', max_length=22),
            preserve_default=False,
        ),
    ]
