# Generated by Django 4.1.2 on 2022-11-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razorpay_payment_id',
            new_name='razorpay_order_id',
        ),
    ]
